/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.controleFinanceiro.view;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import br.com.controleFinanceiro.dto.MovimentacaoDTO;
import br.com.controleFinanceiro.ctr.MovimentacaoCTR;

/**
 *
 * @author gordoni
 */
public class MovimentacaoVIEW extends javax.swing.JInternalFrame {

    MovimentacaoDTO movimentacaoDTO = new MovimentacaoDTO();
    MovimentacaoCTR movimentacaoCTR = new MovimentacaoCTR();

    int gravar_alterar;

    ResultSet rs;
    DefaultTableModel modelo_jtl_consultar_movimentacao;

    /**
     * Creates new form MovimentacaoVIEW
     */
    public MovimentacaoVIEW() {
        initComponents();

        liberarCampos(false);
        liberarBotoes(true, false, false, false, true);

        modelo_jtl_consultar_movimentacao = (DefaultTableModel) jtl_consultar_movimentacao.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formaPagamentoGroup = new javax.swing.ButtonGroup();
        prioridadeGroup = new javax.swing.ButtonGroup();
        statusGroup = new javax.swing.ButtonGroup();
        lblMovimentacao = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        nome_mov = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblFormaPagamento = new javax.swing.JLabel();
        lblStatusasd = new javax.swing.JLabel();
        usuario_mov = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPaneMovimentacao = new javax.swing.JScrollPane();
        jtl_consultar_movimentacao = new javax.swing.JTable();
        lblNomePesquisa = new javax.swing.JLabel();
        pesquisa_nome_mov = new javax.swing.JTextField();
        lblConsultar = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        tipo_mov = new javax.swing.JComboBox<>();
        categoria_mov = new javax.swing.JComboBox<>();
        rbPix = new javax.swing.JRadioButton();
        rbCartao = new javax.swing.JRadioButton();
        rbEspecie = new javax.swing.JRadioButton();
        rbBoleto = new javax.swing.JRadioButton();
        rbOutro = new javax.swing.JRadioButton();
        lblStatus = new javax.swing.JLabel();
        rbPago = new javax.swing.JRadioButton();
        rbPendente = new javax.swing.JRadioButton();
        rbCancelado = new javax.swing.JRadioButton();
        lblPrioridade = new javax.swing.JLabel();
        rbAlta = new javax.swing.JRadioButton();
        rbMedia = new javax.swing.JRadioButton();
        rbBaixa = new javax.swing.JRadioButton();
        lblData = new javax.swing.JLabel();
        data_mov = new javax.swing.JFormattedTextField();
        lblRecorrencia = new javax.swing.JLabel();
        recorrencia_mov = new javax.swing.JComboBox<>();
        textAreaObservacao_mov = new javax.swing.JScrollPane();
        observacao_mov = new javax.swing.JTextPane();
        lblObservacao_mov = new javax.swing.JLabel();
        valor_mov = new javax.swing.JFormattedTextField();

        setClosable(true);
        setMaximizable(true);
        setTitle("Movimentação - CRUD");

        lblMovimentacao.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblMovimentacao.setText("Movimentação");

        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("Nome:");

        nome_mov.setNextFocusableComponent(valor_mov);

        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValor.setText("Valor:");

        lblCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCategoria.setText("Categoria:");

        lblFormaPagamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFormaPagamento.setText("Forma de pagamento:");

        lblStatusasd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatusasd.setText("Usuário:");

        usuario_mov.setNextFocusableComponent(observacao_mov);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleFinanceiro/view/img/novo.png"))); // NOI18N
        btnNovo.setNextFocusableComponent(btnSalvar);
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleFinanceiro/view/img/salvar.png"))); // NOI18N
        btnSalvar.setNextFocusableComponent(btnCancelar);
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleFinanceiro/view/img/cancelar.png"))); // NOI18N
        btnCancelar.setNextFocusableComponent(btnExcluir);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleFinanceiro/view/img/excluir.png"))); // NOI18N
        btnExcluir.setNextFocusableComponent(btnSair);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleFinanceiro/view/img/sair.png"))); // NOI18N
        btnSair.setNextFocusableComponent(pesquisa_nome_mov);
        btnSair.addActionListener(this::btnSairActionPerformed);

        jtl_consultar_movimentacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtl_consultar_movimentacao.setNextFocusableComponent(nome_mov);
        jtl_consultar_movimentacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtl_consultar_movimentacaoMouseClicked(evt);
            }
        });
        jScrollPaneMovimentacao.setViewportView(jtl_consultar_movimentacao);

        lblNomePesquisa.setText("Nome:");

        pesquisa_nome_mov.setNextFocusableComponent(btnPesquisar);

        lblConsultar.setFont(new java.awt.Font("Noto Sans Nerd Font", 1, 24)); // NOI18N
        lblConsultar.setText("Consulta");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleFinanceiro/view/img/pesquisar.png"))); // NOI18N
        btnPesquisar.setNextFocusableComponent(jtl_consultar_movimentacao);
        btnPesquisar.addActionListener(this::btnPesquisarActionPerformed);

        lblTipo.setText("Tipo:");

        tipo_mov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Entrada", "Saída" }));
        tipo_mov.setNextFocusableComponent(categoria_mov);

        categoria_mov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Alimentação", "Moradia", "Transporte", "Saúde", "Educação", "Lazer", "Vestuário", "Salário", "Investimento", "Assinatura", "Outros" }));
        categoria_mov.setNextFocusableComponent(data_mov);

        formaPagamentoGroup.add(rbPix);
        rbPix.setText("Pix");
        rbPix.setNextFocusableComponent(rbCartao);

        formaPagamentoGroup.add(rbCartao);
        rbCartao.setText("Cartão");
        rbCartao.setNextFocusableComponent(rbEspecie);

        formaPagamentoGroup.add(rbEspecie);
        rbEspecie.setText("Espécie");
        rbEspecie.setNextFocusableComponent(rbBoleto);

        formaPagamentoGroup.add(rbBoleto);
        rbBoleto.setText("Boleto");
        rbBoleto.setNextFocusableComponent(rbOutro);

        formaPagamentoGroup.add(rbOutro);
        rbOutro.setText("Outro");
        rbOutro.setNextFocusableComponent(data_mov);

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setText("Status:");

        statusGroup.add(rbPago);
        rbPago.setText("Pago");

        statusGroup.add(rbPendente);
        rbPendente.setText("Pendente");

        statusGroup.add(rbCancelado);
        rbCancelado.setText("Cancelado");

        lblPrioridade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrioridade.setText("Prioridade:");

        prioridadeGroup.add(rbAlta);
        rbAlta.setText("Alta");
        rbAlta.setNextFocusableComponent(rbMedia);

        prioridadeGroup.add(rbMedia);
        rbMedia.setText("Média");
        rbMedia.setNextFocusableComponent(rbBaixa);

        prioridadeGroup.add(rbBaixa);
        rbBaixa.setText("Baixa");
        rbBaixa.setNextFocusableComponent(rbPix);

        lblData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblData.setText("Data:");

        try {
            data_mov.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data_mov.setNextFocusableComponent(recorrencia_mov);

        lblRecorrencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRecorrencia.setText("Recorrência:");

        recorrencia_mov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Não se repete", "Diária", "Semanal", "Quinzenal", "Mensal", "Bimestral", "Trimestral", "Semestral", "Anual" }));
        recorrencia_mov.setNextFocusableComponent(usuario_mov);

        observacao_mov.setNextFocusableComponent(btnNovo);
        textAreaObservacao_mov.setViewportView(observacao_mov);

        lblObservacao_mov.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblObservacao_mov.setText("Observação:");

        valor_mov.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(lblMovimentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConsultar)
                .addGap(221, 221, 221))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 50, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblStatusasd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblObservacao_mov, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblFormaPagamento, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nome_mov, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(valor_mov)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblTipo)
                                    .addGap(18, 18, 18)
                                    .addComponent(tipo_mov, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categoria_mov, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrioridade)
                                .addGap(18, 18, 18)
                                .addComponent(rbAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbMedia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbBaixa))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(usuario_mov, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(data_mov, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblRecorrencia)
                                    .addGap(18, 18, 18)
                                    .addComponent(recorrencia_mov, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbPix)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rbCartao)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rbEspecie)
                                            .addGap(40, 40, 40)
                                            .addComponent(lblStatus))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbBoleto)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rbOutro)))
                                    .addGap(18, 18, 18)
                                    .addComponent(rbPago)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbPendente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbCancelado)))
                            .addComponent(textAreaObservacao_mov, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovo)
                        .addGap(30, 30, 30)
                        .addComponent(btnSalvar)
                        .addGap(30, 30, 30)
                        .addComponent(btnCancelar)
                        .addGap(30, 30, 30)
                        .addComponent(btnExcluir)
                        .addGap(30, 30, 30)
                        .addComponent(btnSair)
                        .addGap(186, 186, 186)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomePesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisa_nome_mov)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConsultar)
                            .addComponent(lblMovimentacao))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pesquisa_nome_mov, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addComponent(lblNomePesquisa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneMovimentacao))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(nome_mov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(lblTipo)
                            .addComponent(tipo_mov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valor_mov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria)
                            .addComponent(categoria_mov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrioridade)
                            .addComponent(rbAlta)
                            .addComponent(rbMedia)
                            .addComponent(rbBaixa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFormaPagamento)
                                    .addComponent(rbPix)
                                    .addComponent(rbCartao)
                                    .addComponent(rbEspecie)
                                    .addComponent(lblStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbBoleto)
                                    .addComponent(rbOutro))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblData)
                                    .addComponent(data_mov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRecorrencia)
                                    .addComponent(recorrencia_mov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblStatusasd)
                                    .addComponent(usuario_mov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbPago)
                                .addComponent(rbPendente)
                                .addComponent(rbCancelado)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObservacao_mov)
                            .addComponent(textAreaObservacao_mov, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo)
                            .addComponent(btnSalvar)
                            .addComponent(btnCancelar)
                            .addComponent(btnExcluir)
                            .addComponent(btnSair))))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        liberarCampos(true);
        liberarBotoes(false, true, true, false, true);
        gravar_alterar = 1;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (gravar_alterar == 1) {
            gravar();
            gravar_alterar = 0;
            preencherTabela(pesquisa_nome_mov.getText());
        } else if (gravar_alterar == 2) {
            alterar();
            gravar_alterar = 0;
            preencherTabela("");
        } else {
            JOptionPane.showMessageDialog(null, "Erro no Sistema");
        }

        limparCampos();
        liberarCampos(false);
        liberarBotoes(true, false, false, false, true);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        preencherTabela(pesquisa_nome_mov.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jtl_consultar_movimentacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtl_consultar_movimentacaoMouseClicked
        preencheCampos(Integer.parseInt(String.valueOf(
                jtl_consultar_movimentacao.getValueAt(
                        jtl_consultar_movimentacao.getSelectedRow(), 0))));
        liberarBotoes(false, true, true, true, true);
    }//GEN-LAST:event_jtl_consultar_movimentacaoMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
        liberarCampos(false);
        modelo_jtl_consultar_movimentacao.setNumRows(0);
        liberarBotoes(true, false, false, false, true);
        gravar_alterar = 0;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluir();

        limparCampos();
        liberarCampos(false);
        liberarBotoes(true, false, false, false, true);
        preencherTabela(pesquisa_nome_mov.getText());
    }//GEN-LAST:event_btnExcluirActionPerformed

    public void setPosition() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    private void liberarCampos(boolean campos) {
        nome_mov.setEnabled(campos);
        valor_mov.setEnabled(campos);
        tipo_mov.setEnabled(campos);
        data_mov.setEnabled(campos);
        categoria_mov.setEnabled(campos);
        rbAlta.setEnabled(campos);
        rbBaixa.setEnabled(campos);
        rbBoleto.setEnabled(campos);
        rbCancelado.setEnabled(campos);
        rbCartao.setEnabled(campos);
        rbEspecie.setEnabled(campos);
        rbMedia.setEnabled(campos);
        rbOutro.setEnabled(campos);
        rbPago.setEnabled(campos);
        rbPendente.setEnabled(campos);
        rbPix.setEnabled(campos);
        recorrencia_mov.setEnabled(campos);
        usuario_mov.setEnabled(campos);
        observacao_mov.setEnabled(campos);
    }

    private void limparCampos() {
        nome_mov.setText("");
        valor_mov.setText("");
        usuario_mov.setText("");
        data_mov.setText("");
        observacao_mov.setText("");

        tipo_mov.setSelectedIndex(0);
        categoria_mov.setSelectedIndex(0);
        recorrencia_mov.setSelectedIndex(0);

        formaPagamentoGroup.clearSelection();
        prioridadeGroup.clearSelection();
        statusGroup.clearSelection();
    }

    private void liberarBotoes(boolean novo, boolean salvar, boolean cancelar, boolean excluir, boolean sair) {
        btnNovo.setEnabled(novo);
        btnSalvar.setEnabled(salvar);
        btnCancelar.setEnabled(cancelar);
        btnExcluir.setEnabled(excluir);
        btnSair.setEnabled(sair);
    }

    private void gravar() {
        try {
            movimentacaoDTO.setNome_mov(nome_mov.getText());
            movimentacaoDTO.setValor_mov(Double.parseDouble(valor_mov.getText()));
            movimentacaoDTO.setTipo_mov(tipo_mov.getSelectedItem().toString());
            movimentacaoDTO.setCategoria_mov(categoria_mov.getSelectedItem().toString());
            movimentacaoDTO.setData_mov(data_mov.getText());
            movimentacaoDTO.setRecorrencia_mov(recorrencia_mov.getSelectedItem().toString());
            movimentacaoDTO.setUsuario_mov(usuario_mov.getText());
            movimentacaoDTO.setObservacao_mov(observacao_mov.getText());
            
            if (rbPix.isSelected()) {
                movimentacaoDTO.setForma_pagamento_mov("Pix");
            } else if (rbCartao.isSelected()) {
                movimentacaoDTO.setForma_pagamento_mov("Cartão");
            } else if (rbEspecie.isSelected()) {
                movimentacaoDTO.setForma_pagamento_mov("Espécie");
            } else if (rbBoleto.isSelected()) {
                movimentacaoDTO.setForma_pagamento_mov("Boleto");
            } else {
                movimentacaoDTO.setForma_pagamento_mov("Outro");
            }

            if (rbPago.isSelected()) {
                movimentacaoDTO.setStatus_mov("Pago");
            } else if (rbPendente.isSelected()) {
                movimentacaoDTO.setStatus_mov("Pendente");
            } else {
                movimentacaoDTO.setStatus_mov("Cancelado");
            }

            if (rbAlta.isSelected()) {
                movimentacaoDTO.setPrioridade_mov("Alta");
            } else if (rbMedia.isSelected()) {
                movimentacaoDTO.setPrioridade_mov("Média");
            } else {
                movimentacaoDTO.setPrioridade_mov("Baixa");
            }

            JOptionPane.showMessageDialog(null,
                    movimentacaoCTR.inserirMovimentacao(movimentacaoDTO));

        } catch (Exception e) {
            System.err.println("Erro ao Gravar: " + e.getMessage());
        }
    }

    private void preencherTabela(String nome_mov) {
        try {
            modelo_jtl_consultar_movimentacao.setNumRows(0);

            movimentacaoDTO.setNome_mov(nome_mov);
            rs = movimentacaoCTR.consultarMovimentacao(movimentacaoDTO, 1);

            while (rs.next()) {
                modelo_jtl_consultar_movimentacao.addRow(new Object[]{
                    rs.getInt("id_mov"),
                    rs.getString("nome_mov"),
                    rs.getDouble("valor_mov")
                });
            }

        } catch (Exception e) {
            System.err.println("Erro ao preencher tabela: " + e.getMessage());
        } finally {
            movimentacaoCTR.CloseDB();
        }
    }

    private void preencheCampos(int id_mov) {
        try {
            movimentacaoDTO.setId_mov(id_mov);
            rs = movimentacaoCTR.consultarMovimentacao(movimentacaoDTO, 2);

            if (rs.next()) {
                limparCampos();

                nome_mov.setText(rs.getString("nome_mov"));
                valor_mov.setText(String.valueOf(rs.getDouble("valor_mov")));
                tipo_mov.setSelectedItem(rs.getString("tipo_mov"));
                categoria_mov.setSelectedItem(rs.getString("categoria_mov"));
                data_mov.setText(rs.getString("data_mov"));
                recorrencia_mov.setSelectedItem(rs.getString("recorrencia_mov"));
                usuario_mov.setText(rs.getString("usuario_mov"));
                observacao_mov.setText(rs.getString("observacao_mov"));

                String forma = rs.getString("forma_pagamento_mov");
                if (forma.equals("Pix")) {
                    rbPix.setSelected(true);
                } else if (forma.equals("Cartão")) {
                    rbCartao.setSelected(true);
                } else if (forma.equals("Espécie")) {
                    rbEspecie.setSelected(true);
                } else if (forma.equals("Boleto")) {
                    rbBoleto.setSelected(true);
                } else {
                    rbOutro.setSelected(true);
                }

                String status = rs.getString("status_mov");
                if (status.equals("Pago")) {
                    rbPago.setSelected(true);
                } else if (status.equals("Pendente")) {
                    rbPendente.setSelected(true);
                } else {
                    rbCancelado.setSelected(true);
                }

                String prioridade = rs.getString("prioridade_mov");
                if (prioridade.equals("Alta")) {
                    rbAlta.setSelected(true);
                } else if (prioridade.equals("Média")) {
                    rbMedia.setSelected(true);
                } else {
                    rbBaixa.setSelected(true);
                }

                gravar_alterar = 2;
                liberarCampos(true);
            }

        } catch (Exception e) {
            System.err.println("Erro ao preencher campos: " + e.getMessage());
        } finally {
            movimentacaoCTR.CloseDB();
        }
    }

    private void alterar() {
        try {
            movimentacaoDTO.setNome_mov(nome_mov.getText());
            movimentacaoDTO.setValor_mov(Double.parseDouble(valor_mov.getText()));
            movimentacaoDTO.setTipo_mov(tipo_mov.getSelectedItem().toString());
            movimentacaoDTO.setCategoria_mov(categoria_mov.getSelectedItem().toString());
            movimentacaoDTO.setData_mov(data_mov.getText());
            movimentacaoDTO.setRecorrencia_mov(recorrencia_mov.getSelectedItem().toString());
            movimentacaoDTO.setUsuario_mov(usuario_mov.getText());
            movimentacaoDTO.setObservacao_mov(observacao_mov.getText());
          
            if (rbPix.isSelected()) {
                movimentacaoDTO.setForma_pagamento_mov("Pix");
            } else if (rbCartao.isSelected()) {
                movimentacaoDTO.setForma_pagamento_mov("Cartão");
            } else if (rbEspecie.isSelected()) {
                movimentacaoDTO.setForma_pagamento_mov("Espécie");
            } else if (rbBoleto.isSelected()) {
                movimentacaoDTO.setForma_pagamento_mov("Boleto");
            } else {
                movimentacaoDTO.setForma_pagamento_mov("Outro");
            }

            if (rbPago.isSelected()) {
                movimentacaoDTO.setStatus_mov("Pago");
            } else if (rbPendente.isSelected()) {
                movimentacaoDTO.setStatus_mov("Pendente");
            } else {
                movimentacaoDTO.setStatus_mov("Cancelado");
            }

            if (rbAlta.isSelected()) {
                movimentacaoDTO.setPrioridade_mov("Alta");
            } else if (rbMedia.isSelected()) {
                movimentacaoDTO.setPrioridade_mov("Média");
            } else {
                movimentacaoDTO.setPrioridade_mov("Baixa");
            }

            JOptionPane.showMessageDialog(null,
                    movimentacaoCTR.alterarMovimentacao(movimentacaoDTO));

        } catch (Exception e) {
            System.err.println("Erro ao Atualizar: " + e.getMessage());
        }
    }

    private void excluir() {
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o Movimentacao?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, movimentacaoCTR.excluirMovimentacao(movimentacaoDTO));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> categoria_mov;
    private javax.swing.JFormattedTextField data_mov;
    private javax.swing.ButtonGroup formaPagamentoGroup;
    private javax.swing.JScrollPane jScrollPaneMovimentacao;
    private javax.swing.JTable jtl_consultar_movimentacao;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblConsultar;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblMovimentacao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomePesquisa;
    private javax.swing.JLabel lblObservacao_mov;
    private javax.swing.JLabel lblPrioridade;
    private javax.swing.JLabel lblRecorrencia;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusasd;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField nome_mov;
    private javax.swing.JTextPane observacao_mov;
    private javax.swing.JTextField pesquisa_nome_mov;
    private javax.swing.ButtonGroup prioridadeGroup;
    private javax.swing.JRadioButton rbAlta;
    private javax.swing.JRadioButton rbBaixa;
    private javax.swing.JRadioButton rbBoleto;
    private javax.swing.JRadioButton rbCancelado;
    private javax.swing.JRadioButton rbCartao;
    private javax.swing.JRadioButton rbEspecie;
    private javax.swing.JRadioButton rbMedia;
    private javax.swing.JRadioButton rbOutro;
    private javax.swing.JRadioButton rbPago;
    private javax.swing.JRadioButton rbPendente;
    private javax.swing.JRadioButton rbPix;
    private javax.swing.JComboBox<String> recorrencia_mov;
    private javax.swing.ButtonGroup statusGroup;
    private javax.swing.JScrollPane textAreaObservacao_mov;
    private javax.swing.JComboBox<String> tipo_mov;
    private javax.swing.JTextField usuario_mov;
    private javax.swing.JFormattedTextField valor_mov;
    // End of variables declaration//GEN-END:variables
}
